<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Barcode - {{ $sku }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #fff;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 15px;
        }

        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #333;
        }

        .header p {
            margin: 5px 0 0 0;
            color: #666;
            font-size: 12px;
        }

        .barcode-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 20px;
            margin-top: 20px;
            padding: 0 15px;
        }

        .barcode-item {
            border: 1px solid #ddd;
            padding: 20px;
            text-align: center;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            margin-bottom: 15px;
        }

        .barcode-image {
            margin-bottom: 10px;
        }

        .barcode-image img {
            max-width: 100%;
            height: auto;
        }

        .product-name {
            font-weight: bold;
            font-size: 14px;
            margin-bottom: 5px;
            color: #333;
            word-wrap: break-word;
        }

        .product-sku {
            font-size: 12px;
            color: #666;
            font-family: 'Courier New', monospace;
            letter-spacing: 1px;
        }

        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 10px;
            color: #999;
            border-top: 1px solid #eee;
            padding-top: 15px;
        }

        /* Responsive grid for different quantities */
        @media print {
            body { margin: 0; }
            .barcode-item {
                break-inside: avoid;
                page-break-inside: avoid;
            }
        }

        /* Always show 4 barcodes per row */
        .barcode-grid {
            grid-template-columns: repeat(4, 1fr) !important;
            gap: 20px !important;
        }

        .barcode-item {
            padding: 15px;
        }

        .product-name {
            font-size: 14px;
            font-weight: bold;
        }

        .product-sku {
            font-size: 12px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Product Barcodes</h1>
        <p>Generated on {{ $generated_at }} | Quantity: {{ $quantity }}</p>
    </div>

    <div class="barcode-grid">
        @for($i = 1; $i <= $quantity; $i++)
            <div class="barcode-item">
                <div class="barcode-image">
                    <img src="data:image/png;base64,{{ $barcode }}" alt="Barcode for {{ $sku }}">
                </div>
                <div class="product-name">{{ $name }}</div>
                <div class="product-sku">{{ $sku }}</div>
            </div>
        @endfor
    </div>

    <div class="footer">
        <p>Generated by {{ config('app.name') }}</p>
        <p>This document contains {{ $quantity }} barcode(s) for product: {{ $name }} ({{ $sku }})</p>
    </div>

</body>
</html>
